import React, {useState} from '/Volumes/code/YUMIV2/frontend/node_modules/react/index.js';
import {createRoot} from '/Volumes/code/YUMIV2/frontend/node_modules/react-dom/client.js';
import PlusOutlined from '/Volumes/code/YUMIV2/frontend/node_modules/@ant-design/icons/es/icons/PlusOutlined.js';
import {ConfigProvider, App, Button, Card, Table, Tag, Badge, Select, Input, InputNumber, DatePicker, Form, Space, Typography, Segmented, Descriptions, Alert, Empty, Modal} from '/Volumes/code/YUMIV2/frontend/node_modules/antd/es/index.js';
import dayjs from '/Volumes/code/YUMIV2/frontend/node_modules/dayjs/dayjs.min.js';
const {Text,Title}=Typography;
const today='2026-09-25';
const orders=[{value:'C000126',label:'C000126 · 林女士',items:[{value:'a',label:'01 · 奶油小熊 · 25cm / 米白',name:'奶油小熊',spec:'25cm / 米白',demand:1000},{value:'b',label:'02 · 垂耳兔 · 30cm / 浅粉',name:'垂耳兔',spec:'30cm / 浅粉',demand:600}]},{value:'C000127',label:'C000127 · 星禾礼品',items:[{value:'c',label:'01 · 圆脸猫 · 20cm / 灰色',name:'圆脸猫',spec:'20cm / 灰色',demand:800}]}];
const staff=['陈师傅','李师傅','王师傅','赵师傅'];
const employeeColors={陈师傅:'blue',李师傅:'purple',王师傅:'green',赵师傅:'orange'};
const employeeClass=name=>`employee-${employeeColors[name]||'slate'}`;
const nodes=['制作','捏毛装袋','缝边剪袋'];
const seed=[
{id:1,no:'PN000031',date:'2026-09-24',employee:'陈师傅',order:'C000126',item:'a',node:'制作',type:'普通生产',quantity:300,status:'已核实',result:{completed:280,rework:0,scrap:0,note:'剩余20件尚未安排。'},follow:20},
{id:2,no:'PN000032',date:today,employee:'李师傅',order:'C000126',item:'a',node:'制作',type:'普通生产',quantity:200,status:'未核实'},
{id:3,no:'PN000033',date:'2026-09-26',employee:'王师傅',order:'C000126',item:'a',node:'制作',type:'普通生产',quantity:300,status:'未核实'},
{id:4,no:'PN000034',date:today,employee:'赵师傅',order:'C000126',item:'a',node:'捏毛装袋',type:'普通生产',quantity:200,status:'未核实'},
{id:5,no:'OS000011',date:today,employee:'王师傅',type:'其他排班',work:'整理仓库',quantity:120,status:'未核实'},
{id:6,no:'PN000035',date:today,employee:'陈师傅',order:'C000127',item:'c',node:'制作',type:'普通生产',quantity:200,status:'已核实',result:{completed:200,rework:10,scrap:5,note:'接缝待返修。'}},
{id:7,no:'PN000030',date:'2026-09-23',employee:'赵师傅',order:'C000126',item:'a',node:'制作',type:'普通生产',quantity:100,status:'已取消',reason:'人员调整，已重新安排。'}];
function itemInfo(id){return orders.flatMap(x=>x.items).find(x=>x.value===id)}
const unit=r=>r.type==='其他排班'?'分钟':'件';
const hasIssue=r=>r.follow>0||r.result?.rework>0||r.result?.scrap>0;
function Demo(){
 const {message,modal}=App.useApp();
 const [rows,setRows]=useState(seed); const [page,setPage]=useState('list'); const [selected,setSelected]=useState(null); const [createKey,setCreateKey]=useState(0); const [prefill,setPrefill]=useState(null);
 const [filter,setFilter]=useState('全部'); const [employee,setEmployee]=useState(); const [search,setSearch]=useState(''); const [range,setRange]=useState(null); const [view,setView]=useState('today');
 const weekDays=['2026-09-21','2026-09-22','2026-09-23','2026-09-24','2026-09-25','2026-09-26','2026-09-27'];
 const weekLabels=['周一','周二','周三','周四','周五','周六','周日'];
 const goList=()=>{setPage('list');setSelected(null)};
 const goCreate=(context=null)=>{setPrefill(context);setCreateKey(x=>x+1);setPage('create')};
 const show=(r,p='detail')=>{setSelected(r.id);setPage(p)};
 const current=rows.find(r=>r.id===selected);
 function cancel(r){modal.confirm({title:'取消这条排班？',content:'演示中保留原记录，取消后数量不再占用。',okText:'确认取消',cancelText:'返回',onOk(){setRows(rs=>rs.map(x=>x.id===r.id?{...x,status:'已取消',reason:'演示取消'}:x));message.success('排班已取消（演示）')}})}
 function title(r){return r.type==='其他排班'?r.work:`${itemInfo(r.item)?.name} · ${r.node}`}
 function status(r){return <Space size={4}><Tag color={r.status==='已核实'?'green':r.status==='未核实'?'blue':'default'}>{r.status}</Tag>{hasIssue(r)&&r.status!=='已取消'&&<Tag color="orange">需处理</Tag>}</Space>}
 const columns=[{title:'计划日期',dataIndex:'date',width:115},{title:'执行员工',dataIndex:'employee',width:95},{title:'工作内容',key:'work',render:(_,r)=><div><Button type="link" className="work-link" onClick={()=>show(r)}>{title(r)}</Button><div className="sub">{r.order?`${r.order} · ${itemInfo(r.item)?.spec} · ${r.no}`:r.no}</div></div>},{title:'类型',dataIndex:'type',width:105},{title:'计划',width:90,render:(_,r)=>`${r.quantity} ${unit(r)}`},{title:'核实完成',width:110,render:(_,r)=>r.result?<><b>{r.result.completed}</b> {unit(r)}{r.quantity>r.result.completed&&<div className="warning">未完成 {r.quantity-r.result.completed}</div>}</>:'—'},{title:'状态',width:160,render:(_,r)=>status(r)},{title:'操作',width:140,render:(_,r)=><Space size={0}><Button type="link" onClick={()=>show(r)}>查看</Button>{r.status==='未核实'?<Button type="link" onClick={()=>show(r,'verify')}>核实</Button>:r.follow>0?<Button type="link" onClick={()=>goCreate({order:r.order,item:r.item,node:r.node,from:r.id})}>安排剩余</Button>:null}</Space>}];
 const allFiltered=rows.filter(r=>(filter==='全部'||filter==='需要处理'&&hasIssue(r)||r.status===filter)&&(!employee||r.employee===employee)&&(!search||`${title(r)} ${r.order||''} ${r.no}`.includes(search))&&(!range||r.date>=range[0].format('YYYY-MM-DD')&&r.date<=range[1].format('YYYY-MM-DD')));
 const filtered=view==='today'?allFiltered.filter(r=>r.date===today):allFiltered;
 const weekRows=rows.filter(r=>(r.date>=weekDays[0]&&r.date<=weekDays[6])&&r.status!=='已取消'&&(!employee||r.employee===employee)&&(filter==='全部'||filter==='需要处理'&&hasIssue(r)||r.status===filter)&&(!search||`${title(r)} ${r.order||''} ${r.no} ${r.employee}`.includes(search)));
 function todayRow(r){return <div className={`today-row ${r.status==='已核实'?'is-done':''}`} key={r.id}><div className="today-status"><div><b>{title(r)}</b><span>{r.employee} · {r.order?`${r.order} · ${itemInfo(r.item)?.spec}`:r.no}</span></div></div><div className="today-plan"><b>{r.quantity} {unit(r)}</b><span>计划数量</span></div><div className="today-result">{r.result?<><b>{r.result.completed} {unit(r)}</b><span>{r.quantity>r.result.completed?`未完成 ${r.quantity-r.result.completed} ${unit(r)}`:'已全部完成'}</span></>:<><b>—</b><span>尚未核实</span></>}</div><div className="today-row-status">{status(r)}</div><div className="today-actions"><Button type="link" onClick={()=>show(r)}>查看</Button>{r.status==='未核实'?<Button type="primary" size="small" onClick={()=>show(r,'verify')}>核实</Button>:r.follow>0?<Button type="link" onClick={()=>goCreate({order:r.order,item:r.item,node:r.node,from:r.id})}>安排剩余</Button>:null}</div></div>}
 const todayGroups=staff.map(person=>({person,items:filtered.filter(r=>r.employee===person)})).filter(group=>group.items.length>0);
 const todayView=<Card className="today-card"><div className="today-summary"><div><span>今日排班</span><strong>{filtered.length}<small> 条</small></strong></div><div className="summary-blue"><span>待核实</span><strong>{filtered.filter(r=>r.status==='未核实').length}<small> 条</small></strong></div><div className="summary-green"><span>已核实</span><strong>{filtered.filter(r=>r.status==='已核实').length}<small> 条</small></strong></div><div className="summary-orange"><span>需要处理</span><strong>{filtered.filter(hasIssue).length}<small> 条</small></strong></div></div><div className="today-toolbar"><Segmented value={filter} onChange={setFilter} options={['全部','未核实','已核实','需要处理','已取消']}/><Space><Select allowClear placeholder="全部员工" value={employee} onChange={setEmployee} options={staff.map(value=>({value,label:value}))} style={{width:140}}/><Input allowClear placeholder="搜索订单、产品、计划编号" value={search} onChange={e=>setSearch(e.target.value)} style={{width:250}}/></Space></div>{todayGroups.length===0?<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="今天没有符合条件的排班"/>:todayGroups.map(group=><section className="employee-group" key={group.person}><div className="employee-heading"><Space size={8} align="center"><Badge color={employeeColors[group.person]} text={<Text strong>{group.person}</Text>}/><Text type="secondary">{group.items.length} 条安排</Text></Space><Button type="link" icon={<PlusOutlined/>} onClick={()=>goCreate({})}>给此员工安排</Button></div>{group.items.map(todayRow)}</section>)}</Card>;
 function weekCard(r){return <button className={`week-card ${employeeClass(r.employee)} ${r.status==='已核实'?'done':''} ${hasIssue(r)?'issue':''}`} onClick={()=>show(r)}><div className="week-card-employee"><Badge color={employeeColors[r.employee]} text={r.employee}/></div><div className="week-card-status">{status(r)}</div><strong>{title(r)}</strong><span>{r.order?`${r.order} · ${itemInfo(r.item)?.spec}`:r.no}</span><small>{r.result?`已核实 ${r.result.completed}${unit(r)}${r.quantity>r.result.completed?` · 未完成 ${r.quantity-r.result.completed}${unit(r)}`:''}`:'尚未核实'}</small></button>}
 const calendar=<Card className="calendar-card"><div className="calendar-toolbar"><Space><Button onClick={()=>message.info('演示固定展示 9月21日—9月27日')}>‹</Button><b>2026年9月21日 — 9月27日</b><Button onClick={()=>message.info('演示固定展示 9月21日—9月27日')}>›</Button></Space><Space><Select allowClear placeholder="全部员工" value={employee} onChange={setEmployee} options={staff.map(value=>({value,label:value}))} style={{width:140}}/><Select allowClear placeholder="全部状态" value={filter==='全部'?undefined:filter} onChange={value=>setFilter(value||'全部')} options={['未核实','已核实','需要处理'].map(value=>({value,label:value}))} style={{width:120}}/><Button onClick={()=>goCreate()}>新建排班</Button></Space></div><div className="week-head">{weekDays.map((d,i)=><div className={d===today?'today':''} key={d}><b>{weekLabels[i]}</b><span>{d.slice(5)}</span><small>{weekRows.filter(r=>r.date===d).length} 条安排</small></div>)}</div><div className="week-grid">{weekDays.map(d=><div className={`day-cell ${d===today?'today':''}`} key={d}><div className="day-items">{weekRows.filter(r=>r.date===d).map(weekCard)}</div><Button type="text" className="add-day" icon={<PlusOutlined/>} onClick={()=>goCreate({})}>安排</Button></div>)}</div></Card>;
 return <div className="app"><aside><div className="brand"><span className="brandmark">Y</span> YUMI <small>业务管理</small></div><div className="nav-caption">工作空间</div><div className="nav-muted">订单管理</div><div className="nav-active">生产排班</div><div className="nav-muted">库存管理</div><div className="nav-muted">发货管理</div><div className="nav-muted">售后管理</div><div className="sidebar-foot">交互方案 A<br/><span>演示数据 · 不连接真实业务</span></div></aside><div className="main"><header><span>工作空间 <span className="slash">/</span> 生产排班 {page!=='list'&&<><span className="slash">/</span>{page==='create'?'新建排班':page==='verify'?'核实完成情况':'排班详情'}</>}</span><Space><Tag>交互演示</Tag><span className="admin">管理员</span></Space></header><main>
 {page==='list'&&<><div className="page-heading"><div><Title level={4}>{view==='today'?'今日排班':'生产排班'}</Title><Text type="secondary">{view==='today'?'今天要做什么、哪些还没核实、哪些需要处理。':'查询全部历史与未来排班记录。'}</Text></div><Button type="primary" onClick={()=>goCreate()}>新建排班</Button></div><div className="view-tabs"><Segmented value={view} onChange={setView} options={[{label:'今日排班',value:'today'},{label:'排班周历',value:'calendar'},{label:'全部记录',value:'all'}]}/><Text type="secondary">同一批排班 · 切换视角不改变数据</Text></div>{view==='calendar'?calendar:view==='today'?todayView:<Card><div className="toolbar"><Segmented value={filter} onChange={setFilter} options={['全部','未核实','已核实','需要处理','已取消']}/><Text type="secondary">共 {filtered.length} 条</Text></div><Space wrap className="filters"><DatePicker.RangePicker value={range} onChange={setRange} placeholder={['开始日期','结束日期']}/><Select allowClear placeholder="全部员工" value={employee} onChange={setEmployee} options={staff.map(value=>({value,label:value}))} style={{width:140}}/><Input allowClear placeholder="搜索订单、产品、计划编号" value={search} onChange={e=>setSearch(e.target.value)} style={{width:250}}/></Space><Table rowKey="id" columns={columns} dataSource={filtered} pagination={{pageSize:8,showSizeChanger:false}} scroll={{x:1060}}/></Card>}</>}
 {page==='create'&&<Create key={createKey} rows={rows} prefill={prefill} onBack={goList} onSave={(r,again)=>{setRows(rs=>[...rs.map(x=>prefill?.from===x.id?{...x,follow:Math.max(0,(x.follow||0)-r.quantity)}:x),r]);if(!again)show(r);message.success('排班已保存，已有安排已更新（演示）')}}/>}
 {page==='detail'&&current&&<><div className="page-heading"><div><Button type="link" className="back" onClick={goList}>返回排班列表</Button><Title level={4}>排班详情 <span className="heading-no">{current.no}</span></Title></div><Space>{current.status==='未核实'&&<><Button danger onClick={()=>cancel(current)}>取消排班</Button><Button type="primary" onClick={()=>setPage('verify')}>核实完成情况</Button></>}</Space></div><Card title="安排内容" extra={status(current)}><Descriptions column={3} items={[{key:1,label:'执行员工',children:current.employee},{key:2,label:'计划日期',children:current.date},{key:3,label:'排班类型',children:current.type},{key:4,label:'工作内容',children:title(current)},{key:5,label:'关联订单',children:current.order||'—'},{key:6,label:'计划安排',children:`${current.quantity} ${unit(current)}`},{key:7,label:'备注',children:current.note||'—'}]}/></Card><Card title="完成核实" className="section-card">{current.result?<><Descriptions column={3} items={[{key:1,label:'实际完成',children:`${current.result.completed} ${unit(current)}`},...(current.type==='其他排班'?[]:[{key:2,label:'其中合格',children:`${current.result.completed-current.result.rework-current.result.scrap} 件`},{key:3,label:'其中返工',children:`${current.result.rework} 件`},{key:4,label:'其中报废',children:`${current.result.scrap} 件`}]),{key:5,label:'未完成',children:`${Math.max(0,current.quantity-current.result.completed)} ${unit(current)}`},{key:6,label:'核实人',children:'管理员（演示）'},{key:7,label:'核实备注',children:current.result.note||'—'}]}/>{hasIssue(current)&&<div className="follow"><b>后续处理</b>{current.follow>0&&<div className="follow-row"><span>未完成 {current.follow} 件，尚未重新安排</span><Button onClick={()=>goCreate({order:current.order,item:current.item,node:current.node,from:current.id})}>安排剩余</Button></div>}{current.result.rework>0&&<div className="follow-row"><span>返工 {current.result.rework} 件</span><Text type="secondary">本演示暂不展开返工分支</Text></div>}{current.result.scrap>0&&<div className="follow-row"><span>报废 {current.result.scrap} 件</span><Text type="secondary">本演示暂不展开重做分支</Text></div>}</div>}</>:<Text type="secondary">{current.status==='已取消'?`已取消：${current.reason}`:'尚未核实，完成情况将在核实后显示。'}</Text>}</Card></>}
 {page==='verify'&&current&&<Verify row={current} title={title(current)} onBack={()=>setPage('detail')} onSave={result=>{setRows(rs=>rs.map(r=>r.id===current.id?{...r,status:'已核实',result,follow:r.type==='其他排班'?0:Math.max(0,r.quantity-result.completed)}:r));setPage('detail');message.success('完成情况已核实（演示）')}}/>}
 <div className="demo-foot">仅演示交互与信息布局；刷新页面会恢复示例数据。返工、重做及后台流转不在本次演示中执行。</div>
 </main></div></div>
}
function Create({rows,prefill,onBack,onSave}){
 const {message,modal}=App.useApp(); const [form]=Form.useForm(); const [type,setType]=useState('普通生产'); const [order,setOrder]=useState(prefill?.order); const [item,setItem]=useState(prefill?.item); const [node,setNode]=useState(prefill?.node); const [showCancelled,setShowCancelled]=useState(false); const [future,setFuture]=useState();
 const items=orders.find(o=>o.value===order)?.items||[]; const ready=!!(item&&node); const related=rows.filter(r=>r.item===item&&r.node===node); const valid=related.filter(r=>r.status!=='已取消'&&r.type==='普通生产'); const completed=valid.reduce((s,r)=>s+(r.result?.completed||0),0); const pending=valid.filter(r=>r.status==='未核实').reduce((s,r)=>s+r.quantity,0); const demand=itemInfo(item)?.demand||0; const remaining=Math.max(0,demand-completed-pending); const futureRows=related.filter(r=>r.date>today&&r.status==='未核实'&&r.type==='普通生产'); const upper=type==='超额任务'?(futureRows.find(r=>r.id===future)?.quantity||0):prefill?.from?Math.min(remaining,rows.find(r=>r.id===prefill.from)?.follow||0):remaining;
 const leave=()=>{if(form.isFieldsTouched())modal.confirm({title:'离开新建排班？',content:'尚未保存的本次分配会丢失。',okText:'离开',cancelText:'继续填写',onOk:onBack});else onBack()};
 function changeType(value){setType(value);setFuture(undefined);form.resetFields();form.setFieldValue('date',dayjs(today))}
 async function save(again){try{const v=await form.validateFields();if(type!=='其他排班'&&!ready){message.warning('请先选择订单、产品明细和工序');return}if(type!=='其他排班'&&(!Number.isInteger(v.quantity)||v.quantity>upper)){form.setFields([{name:'quantity',errors:[`本次最多可安排 ${upper} 件`]}]);return}if(type==='其他排班'&&!(v.hours*60+v.minutes>0)){message.warning('计划工时需要大于0');return}const id=Math.max(...rows.map(x=>x.id))+1;onSave({id,no:`${type==='其他排班'?'OS':'PN'}${String(40+id).padStart(6,'0')}`,date:v.date.format('YYYY-MM-DD'),employee:v.employee,type,order:type==='其他排班'?undefined:order,item:type==='其他排班'?undefined:item,node:type==='其他排班'?undefined:node,quantity:type==='其他排班'?v.hours*60+v.minutes:v.quantity,work:v.work,note:v.note,status:'未核实'},again);if(again)form.resetFields(['employee','quantity','note','work','hours','minutes']);}catch{}}
 const historyColumns=[{title:'日期',dataIndex:'date',width:105},{title:'员工',dataIndex:'employee',width:85},{title:'类型',dataIndex:'type',width:90},{title:'计划',dataIndex:'quantity',width:65},{title:'核实完成',width:80,render:(_,r)=>r.result?.completed??'—'},{title:'状态',render:(_,r)=><Tag color={r.status==='已核实'?'green':r.status==='未核实'?'blue':'default'}>{r.status}</Tag>}];
 return <><div className="page-heading"><div><Button type="link" className="back" onClick={leave}>返回排班列表</Button><Title level={4}>新建排班</Title></div><Text type="secondary">先查看已有安排，再分配本次工作</Text></div><Card className="context-card"><div className="type-row"><b>排班类型</b><Segmented value={type} options={['普通生产','超额任务','其他排班']} onChange={changeType}/></div>{type!=='其他排班'&&<div className="context-fields"><div><label>订单</label><Select aria-label="订单" placeholder="选择订单" value={order} options={orders} onChange={v=>{setOrder(v);setItem(undefined);setNode(undefined);setFuture(undefined);form.resetFields(['quantity'])}}/></div><div><label>产品明细</label><Select aria-label="产品明细" placeholder="选择产品明细" disabled={!order} value={item} options={items} onChange={v=>{setItem(v);setNode(undefined);setFuture(undefined);form.resetFields(['quantity'])}}/></div><div><label>工序</label><Select aria-label="工序" placeholder="选择工序" disabled={!item} value={node} options={nodes.map(value=>({value,label:value}))} onChange={v=>{setNode(v);setFuture(undefined);form.resetFields(['quantity'])}}/></div></div>}</Card>
 <div className="create-grid"><Card title={type==='其他排班'?'已有其他排班':'这项工作的已有安排'} extra={type!=='其他排班'&&ready?<Button type="link" size="small" onClick={()=>setShowCancelled(x=>!x)}>{showCancelled?'隐藏已取消':'包含已取消'}</Button>:null}>
 {type==='其他排班'?<><Text type="secondary">其他排班只记录工作内容和工时，不占用订单数量。</Text><Table className="section-card" rowKey="id" pagination={false} dataSource={rows.filter(r=>r.type==='其他排班')} columns={[{title:'日期',dataIndex:'date'},{title:'员工',dataIndex:'employee'},{title:'工作内容',dataIndex:'work'},{title:'计划工时',render:(_,r)=>`${r.quantity} 分钟`}]}/></>:!ready?<div className="empty-context"><Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="选择订单、产品明细和工序后，查看已有安排"/></div>:<><div className="context-name"><b>{itemInfo(item)?.name} · {node}</b><Text type="secondary">{order} · {itemInfo(item)?.spec}</Text></div><div className="metrics">{[['工作需求',demand],['已核实处理',completed],['已安排未核实',pending],['还能安排',remaining]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}<small> 件</small></strong></div>)}</div><div className="table-caption">全部日期的安排 <Text type="secondary">不受本次计划日期限制</Text></div><Table size="middle" rowKey="id" pagination={{pageSize:6,showSizeChanger:false}} columns={historyColumns} dataSource={related.filter(r=>showCancelled||r.status!=='已取消').sort((a,b)=>a.date.localeCompare(b.date))} locale={{emptyText:'尚未安排，可以开始分配任务'}}/>{type==='超额任务'&&<Alert type="info" title="选择未来计划，安排今天提前完成的工作；演示不执行真实预占和流转。"/>}</>}
 </Card><Card title="本次分配" className="allocation"><Form layout="vertical" form={form} initialValues={{date:dayjs(today),hours:1,minutes:0}} requiredMark={false} disabled={type!=='其他排班'&&!ready}>
 {type==='其他排班'&&<Form.Item label="工作内容" name="work" rules={[{required:true,message:'请填写工作内容'}]}><Input placeholder="例如：整理仓库"/></Form.Item>}
 {type==='超额任务'&&<Form.Item label="关联未来计划" name="future" rules={[{required:true,message:'请选择未来计划'}]}><Select placeholder="选择未来计划" onChange={setFuture} options={futureRows.map(r=>({value:r.id,label:`${r.date} · ${r.employee} · ${r.quantity}件`}))}/></Form.Item>}
 <Form.Item label="计划日期" name="date" rules={[{required:true,message:'请选择日期'}]}><DatePicker allowClear={false} disabled={type==='超额任务'} style={{width:'100%'}}/></Form.Item><Form.Item label="执行员工" name="employee" rules={[{required:true,message:'请选择执行员工'}]}><Select placeholder="选择员工" options={staff.map(value=>({value,label:value}))}/></Form.Item>
 {type==='其他排班'?<div className="time-fields"><Form.Item label="小时" name="hours"><InputNumber min={0} max={24} precision={0}/></Form.Item><Form.Item label="分钟" name="minutes"><InputNumber min={0} max={59} precision={0}/></Form.Item></div>:<Form.Item label="计划数量" name="quantity" rules={[{required:true,message:'请填写计划数量'}]} extra={ready?`本次最多可安排 ${upper} 件`:null}><InputNumber aria-label="计划数量" min={1} precision={0} style={{width:'100%'}} placeholder="填写本次分配数量"/></Form.Item>}
 <Form.Item label="备注（选填）" name="note"><Input.TextArea rows={2} placeholder="补充工作要求"/></Form.Item><div className="allocation-actions"><Button type="primary" block onClick={()=>save(true)}>保存并继续安排</Button><Button block onClick={()=>save(false)}>保存并返回详情</Button><Button type="text" block onClick={leave}>取消</Button></div></Form></Card></div></>
}
function Verify({row,title,onBack,onSave}){
 const [form]=Form.useForm(); const {modal}=App.useApp(); const complete=Form.useWatch('completed',form);const rework=Form.useWatch('rework',form)||0;const scrap=Form.useWatch('scrap',form)||0;const other=row.type==='其他排班';
 async function submit(){try{const v=await form.validateFields();if(!other&&(v.completed>row.quantity||v.rework+v.scrap>v.completed)){form.setFields([{name:'completed',errors:['完成数量不得超过计划，且应不少于返工与报废数量之和']}]);return}modal.confirm({title:'确认本次核实结果',content:`实际完成 ${v.completed} ${unit(row)}。核实后这条计划结束${!other&&v.completed<row.quantity?'，未完成部分需要另行安排':''}。`,okText:'确认核实',cancelText:'返回检查',onOk:()=>onSave({...v,rework:v.rework||0,scrap:v.scrap||0})})}catch{}}
 return <><div className="page-heading"><div><Button type="link" className="back" onClick={onBack}>返回排班详情</Button><Title level={4}>核实完成情况</Title></div><Tag>{row.no}</Tag></div><Card title={title}><Descriptions column={3} items={[{key:1,label:'执行员工',children:row.employee},{key:2,label:'计划日期',children:row.date},{key:3,label:'计划安排',children:`${row.quantity} ${unit(row)}`} ]}/></Card><Card title={other?'实际工时':'实际完成情况'} className="section-card"><div className="verify-body"><Form form={form} layout="vertical" requiredMark={false} initialValues={{rework:0,scrap:0}}><div className="verify-fields"><Form.Item label={other?'实际工时（分钟）':'实际完成数量'} name="completed" rules={[{required:true,message:'请填写实际完成情况'}]}><InputNumber aria-label="实际完成数量" min={0} precision={0} style={{width:'100%'}}/></Form.Item>{!other&&<><Form.Item label="其中返工" name="rework"><InputNumber min={0} precision={0} style={{width:'100%'}}/></Form.Item><Form.Item label="其中报废" name="scrap"><InputNumber min={0} precision={0} style={{width:'100%'}}/></Form.Item></>}</div>{!other&&<div className="result-preview"><span>合格 <b>{complete==null?'—':complete-rework-scrap}</b> 件</span><span>未完成 <b>{complete==null?'—':row.quantity-complete}</b> 件</span></div>}<Form.Item label="核实备注（选填）" name="note"><Input.TextArea rows={3} placeholder="说明实际完成情况"/></Form.Item><Text type="secondary">每条计划核实一次；核实后显示实际结果，不会自动安排剩余工作。</Text><div className="verify-actions"><Button type="primary" onClick={submit}>提交核实</Button><Button onClick={onBack}>取消</Button></div></Form></div></Card></>
}
createRoot(document.getElementById('root')).render(<ConfigProvider theme={{token:{colorPrimary:'#1677ff',borderRadius:6,fontSize:14,fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif'},components:{Table:{headerBg:'#fafafa',cellPaddingBlock:16},Card:{headerFontSize:15}}}}><App><Demo/></App></ConfigProvider>);
