CREATE TABLE idempotency_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    idempotency_key VARCHAR(128) NOT NULL,
    admin_username VARCHAR(100) NULL,
    http_method VARCHAR(10) NOT NULL,
    path VARCHAR(255) NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    response_status SMALLINT UNSIGNED NOT NULL,
    response_content_type VARCHAR(128) NULL,
    response_body MEDIUMTEXT NOT NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_idempotency_records_key (idempotency_key),
    KEY idx_idempotency_records_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
