-- 订单模块（阶段三）：订单核心、确认快照、变更单与履约台账。
-- 表归属见 database-design.md §5–6，数量口径见 domain-and-quantity-model.md，列级设计见 order-module-design.md §3。
-- 金额 DECIMAL(19,4)、比例 DECIMAL(9,6)、数量 INT UNSIGNED（非负）；事实表不提供 UPDATE/DELETE 入口。
-- 为阶段四–九预留的列本阶段只建列与约束、不写入。

-- 订单主表：当前有效订单数据 + 金额汇总 + 确认/取消/关闭信息
CREATE TABLE orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no CHAR(7) NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    order_date DATE NOT NULL,
    expected_delivery_date DATE NULL,
    recipient_name VARCHAR(100) NOT NULL,
    recipient_phone VARCHAR(32) NOT NULL,
    region VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL,
    note VARCHAR(1000) NULL,
    goods_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    discount_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    receivable_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    goods_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    profit_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    confirmed_at DATETIME(6) NULL,
    confirmed_by VARCHAR(100) NULL,
    cancelled_at DATETIME(6) NULL,
    cancelled_by VARCHAR(100) NULL,
    cancel_reason VARCHAR(500) NULL,
    closed_at DATETIME(6) NULL,
    closed_by VARCHAR(100) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_orders_order_no (order_no),
    KEY idx_orders_status (status),
    KEY idx_orders_customer (customer_id),
    KEY idx_orders_order_date (order_date),
    KEY idx_orders_request_id (request_id),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_orders_discount_not_negative CHECK (discount_amount >= 0),
    CONSTRAINT ck_orders_discount_within_goods CHECK (discount_amount <= goods_amount + seam_amount),
    CONSTRAINT ck_orders_amounts_not_negative CHECK (goods_amount >= 0 AND seam_amount >= 0
        AND receivable_amount >= 0 AND goods_cost_amount >= 0 AND seam_cost_amount >= 0 AND cost_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 订单明细当前有效值：Q/E、成交价、缝边定制与成本快照
CREATE TABLE order_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    line_no INT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    product_no CHAR(6) NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 0,
    seam_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    unit_price DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    goods_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_type_id BIGINT UNSIGNED NULL,
    seam_type_name VARCHAR(100) NULL,
    seam_unit_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_fee DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    unit_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    goods_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    note VARCHAR(500) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_items_order_line (order_id, line_no),
    KEY idx_order_items_order (order_id),
    KEY idx_order_items_product (product_id),
    KEY idx_order_items_seam_type (seam_type_id),
    KEY idx_order_items_request_id (request_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_order_items_seam_type FOREIGN KEY (seam_type_id) REFERENCES seam_types (id),
    CONSTRAINT ck_order_items_seam_within_quantity CHECK (seam_quantity <= quantity),
    CONSTRAINT ck_order_items_amounts_not_negative CHECK (unit_price >= 0 AND goods_amount >= 0
        AND seam_unit_cost >= 0 AND seam_fee >= 0 AND seam_amount >= 0
        AND unit_cost >= 0 AND goods_cost_amount >= 0 AND seam_cost_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 订单级确认快照：客户、收货、金额与确认信息，确认后不可修改
CREATE TABLE order_confirmation_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    customer_no CHAR(6) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    contact VARCHAR(100) NULL,
    phone VARCHAR(32) NULL,
    recipient_name VARCHAR(100) NOT NULL,
    recipient_phone VARCHAR(32) NOT NULL,
    region VARCHAR(100) NOT NULL,
    address VARCHAR(300) NOT NULL,
    note VARCHAR(1000) NULL,
    goods_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    discount_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    receivable_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    goods_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    profit_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    confirmed_by VARCHAR(100) NOT NULL,
    confirmed_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_confirmation_snapshots_order (order_id),
    KEY idx_order_confirmation_snapshots_request_id (request_id),
    CONSTRAINT fk_order_confirmation_snapshots_order FOREIGN KEY (order_id) REFERENCES orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 明细级确认快照：商品识别/星级/成本组成/成交价/数量/缝边参数/冻结流程
CREATE TABLE order_item_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    line_no INT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    product_no CHAR(6) NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    product_note VARCHAR(1000) NULL,
    image_file_id BIGINT UNSIGNED NULL,
    star_level_id BIGINT UNSIGNED NULL,
    star_name VARCHAR(20) NULL,
    star_std_minutes INT UNSIGNED NULL,
    quantity INT UNSIGNED NOT NULL,
    seam_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    unit_price DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    goods_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_type_id BIGINT UNSIGNED NULL,
    seam_type_name VARCHAR(100) NULL,
    seam_unit_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_fee DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    unit_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    goods_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    seam_cost_amount DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    glue_grams INT UNSIGNED NOT NULL DEFAULT 0,
    glue_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    colorpaste_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    material_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    product_labor_fee DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    packaging_labor_fee DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    box_labor_fee DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    labor_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    other_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    total_cost DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
    flow VARCHAR(200) NOT NULL,
    note VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_item_snapshots_item (order_item_id),
    KEY idx_order_item_snapshots_order (order_id),
    KEY idx_order_item_snapshots_product (product_id),
    KEY idx_order_item_snapshots_request_id (request_id),
    CONSTRAINT fk_order_item_snapshots_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_item_snapshots_item FOREIGN KEY (order_item_id) REFERENCES order_items (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 变更单：已确认订单的表头变更草稿与确认信息
CREATE TABLE order_change_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    change_no CHAR(7) NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    reason VARCHAR(500) NULL,
    new_expected_delivery_date DATE NULL,
    new_recipient_name VARCHAR(100) NULL,
    new_recipient_phone VARCHAR(32) NULL,
    new_region VARCHAR(100) NULL,
    new_address VARCHAR(300) NULL,
    new_note VARCHAR(1000) NULL,
    new_discount_amount DECIMAL(19,4) NULL,
    confirmed_by VARCHAR(100) NULL,
    confirmed_at DATETIME(6) NULL,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_change_orders_change_no (change_no),
    KEY idx_order_change_orders_order (order_id),
    KEY idx_order_change_orders_status (status),
    KEY idx_order_change_orders_request_id (request_id),
    CONSTRAINT fk_order_change_orders_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_order_change_orders_new_discount_not_negative CHECK (new_discount_amount IS NULL
        OR new_discount_amount >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 变更明细：结构化前后值 + 减单超出数量处理方案（不能只保存文本 diff）
CREATE TABLE order_change_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    change_order_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NULL,
    change_type VARCHAR(16) NOT NULL,
    line_no INT UNSIGNED NULL,
    product_id BIGINT UNSIGNED NULL,
    before_quantity INT UNSIGNED NULL,
    after_quantity INT UNSIGNED NULL,
    before_seam_quantity INT UNSIGNED NULL,
    after_seam_quantity INT UNSIGNED NULL,
    before_unit_price DECIMAL(19,4) NULL,
    after_unit_price DECIMAL(19,4) NULL,
    before_seam_type_id BIGINT UNSIGNED NULL,
    after_seam_type_id BIGINT UNSIGNED NULL,
    before_seam_fee DECIMAL(19,4) NULL,
    after_seam_fee DECIMAL(19,4) NULL,
    before_note VARCHAR(500) NULL,
    after_note VARCHAR(500) NULL,
    surplus_disposition VARCHAR(24) NULL,
    surplus_quantity INT UNSIGNED NULL,
    surplus_reason VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    KEY idx_order_change_items_change_order (change_order_id),
    KEY idx_order_change_items_order_item (order_item_id),
    KEY idx_order_change_items_request_id (request_id),
    CONSTRAINT fk_order_change_items_change_order FOREIGN KEY (change_order_id) REFERENCES order_change_orders (id),
    CONSTRAINT fk_order_change_items_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
    CONSTRAINT ck_order_change_items_target CHECK (
        (change_type = 'ADD' AND order_item_id IS NULL AND product_id IS NOT NULL)
        OR (change_type IN ('UPDATE', 'REMOVE') AND order_item_id IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 履约事实：不可变；同一来源记录+来源明细+节点+方向只能入账一次
CREATE TABLE fulfillment_entries (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    entry_type VARCHAR(32) NOT NULL,
    node VARCHAR(32) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    -- 0 = 该来源无明细行；用 0 而非 NULL 以保证唯一键对“无明细来源”同样生效
    source_line_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    business_date DATE NOT NULL,
    operator_username VARCHAR(100) NULL,
    reverses_entry_id BIGINT UNSIGNED NULL,
    note VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_fulfillment_entries_source (source_type, source_id, source_line_id, node, direction),
    KEY idx_fulfillment_entries_item (order_item_id, node, source_type),
    KEY idx_fulfillment_entries_order (order_id),
    KEY idx_fulfillment_entries_reverses (reverses_entry_id),
    KEY idx_fulfillment_entries_request_id (request_id),
    CONSTRAINT fk_fulfillment_entries_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_fulfillment_entries_item FOREIGN KEY (order_item_id) REFERENCES order_items (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- 明细当前数量投影：只能由领域服务在写 fulfillment_entries 的同一事务内更新
CREATE TABLE order_item_fulfillment_balances (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    order_item_id BIGINT UNSIGNED NOT NULL,
    required_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    making_inflow INT UNSIGNED NOT NULL DEFAULT 0,
    packing_inflow INT UNSIGNED NOT NULL DEFAULT 0,
    seam_inflow INT UNSIGNED NOT NULL DEFAULT 0,
    making_planned INT UNSIGNED NOT NULL DEFAULT 0,
    packing_planned INT UNSIGNED NOT NULL DEFAULT 0,
    seam_planned INT UNSIGNED NOT NULL DEFAULT 0,
    verified_processed INT UNSIGNED NOT NULL DEFAULT 0,
    rework_pending INT UNSIGNED NOT NULL DEFAULT 0,
    remake_pending INT UNSIGNED NOT NULL DEFAULT 0,
    shippable_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    shipped_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    finished_surplus_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(128) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_item_fulfillment_balances_item (order_item_id),
    KEY idx_order_item_fulfillment_balances_order (order_id),
    KEY idx_order_item_fulfillment_balances_request_id (request_id),
    CONSTRAINT fk_order_item_fulfillment_balances_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_item_fulfillment_balances_item FOREIGN KEY (order_item_id) REFERENCES order_items (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
